graph TD
 subgraph Chuteira Inteligente
        FSR[Sensor FSR] --> ESP32(Microcontrolador ESP32)
    end

    subgraph Conectividade
        ESP32 -- Wi-Fi / MQTT --> MQTTBroker(MQTT Broker)
    end

    subgraph Plataforma IoT
        MQTTBroker -- IoT Agent for MQTT --> OrionCB(Orion Context Broker)
        OrionCB -- Gerencia Entidades --> Database(Banco de Dados)
    end

    subgraph Aplicação de Visualização
        OrionCB -- API NGSI-LD --> Dashboard(Dashboard Web com Gráficos)
    end

    style FSR fill:#f9f,stroke:#333,stroke-width:2px
    style ESP32 fill:#bbf,stroke:#333,stroke-width:2px
    style MQTTBroker fill:#fcf,stroke:#333,stroke-width:2px
    style OrionCB fill:#ccf,stroke:#333,stroke-width:2px
    style Database fill:#ffc,stroke:#333,stroke-width:2px
    style Dashboard fill:#afa,stroke:#333,stroke-width:2px

    classDef device fill:#f9f,stroke:#333,stroke-width:2px;
    classDef microcontroller fill:#bbf,stroke:#333,stroke-width:2px;
    classDef connectivity fill:#fcf,stroke:#333,stroke-width:2px;
    classDef platform fill:#ccf,stroke:#333,stroke-width:2px;
    classDef database fill:#ffc,stroke:#333,stroke-width:2px;
    classDef visualization fill:#afa,stroke:#333,stroke-width:2px;

    class FSR device
    class ESP32 microcontroller
    class MQTTBroker connectivity
    class OrionCB platform
    class Database database
    class Dashboard visualization

